apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  labels:
    svc-type: cip
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-app
