apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    env: prod
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: sample-container
        image: nginx
        ports:
        - containerPort: 80
