apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  labels:
    svc-type: lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: nginx-app
